// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenProfileServer.Data;

#nullable disable

namespace OpenProfileServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260111121203_Initialization")]
    partial class Initialization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecoveryStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.AccountAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Visibility");

                    b.ToTable("AccountAssets");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.AccountBlock", b =>
                {
                    b.Property<Guid>("BlockerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BlockerId", "BlockedId");

                    b.HasIndex("BlockedId");

                    b.ToTable("AccountBlocks");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.AccountFollower", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("AccountFollowers");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Auth.AccountCredential", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("AccountCredentials");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Auth.AccountEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Email");

                    b.ToTable("AccountEmails");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Auth.AccountSecurity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("BackupCodes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("AccountSecurities");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Auth.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Identifier", "Type", "Code");

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Base.AccountSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowFollowers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultVisibility")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowFollowersList")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowFollowingList")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AccountSettings");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Base.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.ContactMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ContactMethods");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.EducationExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Degree")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonalProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonalProfileId");

                    b.ToTable("EducationExperiences");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.GalleryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("GalleryItems");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.SocialLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("SocialLinks");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.SponsorshipItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("SponsorshipItems");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.WorkExperience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonalProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonalProfileId");

                    b.ToTable("WorkExperiences");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("RecipientId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.OrganizationInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InviteeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InviterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteeId");

                    b.HasIndex("InviterId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("OrganizationInvitations");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.OrganizationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("OrganizationId", "AccountId")
                        .IsUnique();

                    b.ToTable("OrganizationMembers");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.SiteMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Copyright")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteDescription")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SiteMetadata");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.SystemAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Visibility");

                    b.ToTable("SystemAssets");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueType")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Settings.ApplicationSettings", b =>
                {
                    b.HasBaseType("OpenProfileServer.Models.Entities.Base.AccountSettings");

                    b.Property<string>("CallbackUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("RateLimitQuota")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.ToTable("ApplicationSettings", (string)null);
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Settings.OrganizationSettings", b =>
                {
                    b.HasBaseType("OpenProfileServer.Models.Entities.Base.AccountSettings");

                    b.Property<bool>("AllowMemberInvite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultMemberVisibility")
                        .HasColumnType("INTEGER");

                    b.ToTable("OrganizationSettings", (string)null);
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Settings.PersonalSettings", b =>
                {
                    b.HasBaseType("OpenProfileServer.Models.Entities.Base.AccountSettings");

                    b.Property<bool>("ShowLocalTime")
                        .HasColumnType("INTEGER");

                    b.ToTable("PersonalSettings", (string)null);
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Profiles.ApplicationProfile", b =>
                {
                    b.HasBaseType("OpenProfileServer.Models.Entities.Base.Profile");

                    b.Property<Guid?>("DeveloperAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TermsOfServiceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.ToTable("ApplicationProfiles", (string)null);
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Profiles.OrganizationProfile", b =>
                {
                    b.HasBaseType("OpenProfileServer.Models.Entities.Base.Profile");

                    b.Property<DateOnly?>("FoundedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.ToTable("OrganizationProfiles", (string)null);
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Profiles.PersonalProfile", b =>
                {
                    b.HasBaseType("OpenProfileServer.Models.Entities.Base.Profile");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentCompany")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentSchool")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pronouns")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.ToTable("PersonalProfiles", (string)null);
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.AccountAsset", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Asset", b1 =>
                        {
                            b1.Property<Guid>("AccountAssetId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Asset_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Asset_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Asset_Value");

                            b1.HasKey("AccountAssetId");

                            b1.ToTable("AccountAssets");

                            b1.WithOwner()
                                .HasForeignKey("AccountAssetId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Asset")
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.AccountBlock", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Blocked")
                        .WithMany("BlockedBy")
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Blocker")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.AccountFollower", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Auth.AccountCredential", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Account")
                        .WithOne("Credential")
                        .HasForeignKey("OpenProfileServer.Models.Entities.Auth.AccountCredential", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Auth.AccountEmail", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Account")
                        .WithMany("Emails")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Auth.AccountSecurity", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Account")
                        .WithOne("Security")
                        .HasForeignKey("OpenProfileServer.Models.Entities.Auth.AccountSecurity", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Auth.RefreshToken", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Base.AccountSettings", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Account")
                        .WithOne("Settings")
                        .HasForeignKey("OpenProfileServer.Models.Entities.Base.AccountSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Base.Profile", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("OpenProfileServer.Models.Entities.Base.Profile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Avatar", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Avatar_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Avatar_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Avatar_Value");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Background", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Background_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Background_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Background_Value");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Avatar")
                        .IsRequired();

                    b.Navigation("Background")
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.Certificate", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.Profile", "Profile")
                        .WithMany("Certificates")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.ContactMethod", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.Profile", "Profile")
                        .WithMany("Contacts")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Icon", b1 =>
                        {
                            b1.Property<Guid>("ContactMethodId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Icon_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Icon_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Icon_Value");

                            b1.HasKey("ContactMethodId");

                            b1.ToTable("ContactMethods");

                            b1.WithOwner()
                                .HasForeignKey("ContactMethodId");
                        });

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Image", b1 =>
                        {
                            b1.Property<Guid>("ContactMethodId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Image_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Image_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Image_Value");

                            b1.HasKey("ContactMethodId");

                            b1.ToTable("ContactMethods");

                            b1.WithOwner()
                                .HasForeignKey("ContactMethodId");
                        });

                    b.Navigation("Icon")
                        .IsRequired();

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.EducationExperience", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Profiles.PersonalProfile", "PersonalProfile")
                        .WithMany("EducationExperiences")
                        .HasForeignKey("PersonalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Logo", b1 =>
                        {
                            b1.Property<Guid>("EducationExperienceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Logo_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Logo_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Logo_Value");

                            b1.HasKey("EducationExperienceId");

                            b1.ToTable("EducationExperiences");

                            b1.WithOwner()
                                .HasForeignKey("EducationExperienceId");
                        });

                    b.Navigation("Logo")
                        .IsRequired();

                    b.Navigation("PersonalProfile");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.GalleryItem", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.Profile", "Profile")
                        .WithMany("Gallery")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Image", b1 =>
                        {
                            b1.Property<Guid>("GalleryItemId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Image_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Image_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Image_Value");

                            b1.HasKey("GalleryItemId");

                            b1.ToTable("GalleryItems");

                            b1.WithOwner()
                                .HasForeignKey("GalleryItemId");
                        });

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.Project", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.Profile", "Profile")
                        .WithMany("Projects")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Logo", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Logo_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Logo_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Logo_Value");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("Logo")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.SocialLink", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.Profile", "Profile")
                        .WithMany("SocialLinks")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Icon", b1 =>
                        {
                            b1.Property<Guid>("SocialLinkId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Icon_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Icon_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Icon_Value");

                            b1.HasKey("SocialLinkId");

                            b1.ToTable("SocialLinks");

                            b1.WithOwner()
                                .HasForeignKey("SocialLinkId");
                        });

                    b.Navigation("Icon")
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.SponsorshipItem", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.Profile", "Profile")
                        .WithMany("SponsorshipItems")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Icon", b1 =>
                        {
                            b1.Property<Guid>("SponsorshipItemId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Icon_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Icon_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Icon_Value");

                            b1.HasKey("SponsorshipItemId");

                            b1.ToTable("SponsorshipItems");

                            b1.WithOwner()
                                .HasForeignKey("SponsorshipItemId");
                        });

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "QrCode", b1 =>
                        {
                            b1.Property<Guid>("SponsorshipItemId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("QrCode_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QrCode_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("QrCode_Value");

                            b1.HasKey("SponsorshipItemId");

                            b1.ToTable("SponsorshipItems");

                            b1.WithOwner()
                                .HasForeignKey("SponsorshipItemId");
                        });

                    b.Navigation("Icon")
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("QrCode")
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Details.WorkExperience", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Profiles.PersonalProfile", "PersonalProfile")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("PersonalProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Logo", b1 =>
                        {
                            b1.Property<Guid>("WorkExperienceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Logo_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Logo_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Logo_Value");

                            b1.HasKey("WorkExperienceId");

                            b1.ToTable("WorkExperiences");

                            b1.WithOwner()
                                .HasForeignKey("WorkExperienceId");
                        });

                    b.Navigation("Logo")
                        .IsRequired();

                    b.Navigation("PersonalProfile");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Notification", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.OrganizationInvitation", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Invitee")
                        .WithMany()
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Inviter")
                        .WithMany()
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpenProfileServer.Models.Entities.Profiles.OrganizationProfile", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitee");

                    b.Navigation("Inviter");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.OrganizationMember", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Account", "Account")
                        .WithMany("Memberships")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenProfileServer.Models.Entities.Profiles.OrganizationProfile", "Organization")
                        .WithMany("Members")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.SiteMetadata", b =>
                {
                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Favicon", b1 =>
                        {
                            b1.Property<int>("SiteMetadataId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Favicon_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Favicon_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Favicon_Value");

                            b1.HasKey("SiteMetadataId");

                            b1.ToTable("SiteMetadata");

                            b1.WithOwner()
                                .HasForeignKey("SiteMetadataId");
                        });

                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Logo", b1 =>
                        {
                            b1.Property<int>("SiteMetadataId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Logo_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Logo_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Logo_Value");

                            b1.HasKey("SiteMetadataId");

                            b1.ToTable("SiteMetadata");

                            b1.WithOwner()
                                .HasForeignKey("SiteMetadataId");
                        });

                    b.Navigation("Favicon")
                        .IsRequired();

                    b.Navigation("Logo")
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.SystemAsset", b =>
                {
                    b.OwnsOne("OpenProfileServer.Models.ValueObjects.Asset", "Asset", b1 =>
                        {
                            b1.Property<Guid>("SystemAssetId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Tag")
                                .HasMaxLength(512)
                                .HasColumnType("TEXT")
                                .HasColumnName("Asset_Tag");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Asset_Type");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("Asset_Value");

                            b1.HasKey("SystemAssetId");

                            b1.ToTable("SystemAssets");

                            b1.WithOwner()
                                .HasForeignKey("SystemAssetId");
                        });

                    b.Navigation("Asset")
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Settings.ApplicationSettings", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.AccountSettings", null)
                        .WithOne()
                        .HasForeignKey("OpenProfileServer.Models.Entities.Settings.ApplicationSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Settings.OrganizationSettings", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.AccountSettings", null)
                        .WithOne()
                        .HasForeignKey("OpenProfileServer.Models.Entities.Settings.OrganizationSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Settings.PersonalSettings", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.AccountSettings", null)
                        .WithOne()
                        .HasForeignKey("OpenProfileServer.Models.Entities.Settings.PersonalSettings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Profiles.ApplicationProfile", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.Profile", null)
                        .WithOne()
                        .HasForeignKey("OpenProfileServer.Models.Entities.Profiles.ApplicationProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Profiles.OrganizationProfile", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.Profile", null)
                        .WithOne()
                        .HasForeignKey("OpenProfileServer.Models.Entities.Profiles.OrganizationProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Profiles.PersonalProfile", b =>
                {
                    b.HasOne("OpenProfileServer.Models.Entities.Base.Profile", null)
                        .WithOne()
                        .HasForeignKey("OpenProfileServer.Models.Entities.Profiles.PersonalProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Account", b =>
                {
                    b.Navigation("BlockedBy");

                    b.Navigation("BlockedUsers");

                    b.Navigation("Credential");

                    b.Navigation("Emails");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Memberships");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Security");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Base.Profile", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Contacts");

                    b.Navigation("Gallery");

                    b.Navigation("Projects");

                    b.Navigation("SocialLinks");

                    b.Navigation("SponsorshipItems");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Profiles.OrganizationProfile", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("OpenProfileServer.Models.Entities.Profiles.PersonalProfile", b =>
                {
                    b.Navigation("EducationExperiences");

                    b.Navigation("WorkExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
